### ISSUE TITLE
Enable to add docs themes

### ISSUE THREAD

**Issue by helderberto** [robertoachar/workshop-workflow-node#1]
Possibility of creating themes for docs.
The project are awesome @robertoachar. 💯

**Comment by robertoachar** [comment]
Thank you!

I don't understand what you mean. Could you please explain me?

**Comment by helderberto** [comment]
`Stylesheet themes` like `Dracula`, `Material` and others.

**Comment by robertoachar** [comment]
You can customize the entire theme throught `override.styl` and `style.styl`. See: https://vuepress.vuejs.org/default-theme-config/#simple-css-override

You can read more about creating new themes here: https://vuepress.vuejs.org/config/#theming

VuePress uses Prism for syntax highlighting.

**Comment by helderberto** [comment]
Thanks! @robertoachar
